const OPERATOR_COLOR_TOKENS = {
  canvas: "bg-background text-foreground",
  surface: "bg-card text-card-foreground",
  surfaceMuted: "bg-card/70 text-card-foreground",
  muted: "bg-muted/45 text-muted-foreground",
  accent: "bg-accent text-accent-foreground",
  borderQuiet: "ring-1 ring-border/45",
  borderSubtle: "ring-1 ring-border/60",
  divider: "border-border/60"
} as const;

const OPERATOR_SIZE_TOKENS = {
  appHeaderHeight: "h-11",
  appMainInset: "p-3 sm:p-4 lg:p-5",
  pageMaxWidth: "max-w-[1360px]",
  panelPadding: "p-3 sm:p-4",
  panelGap: "gap-3",
  contentGap: "gap-2",
  compactContentGap: "gap-1",
  rowGap: "gap-2"
} as const;

const OPERATOR_RADIUS_TOKENS = {
  control: "rounded-md",
  field: "rounded-md",
  panel: "rounded-lg",
  badge: "rounded-sm"
} as const;

export const OPERATOR_DESIGN_TOKENS = {
  color: OPERATOR_COLOR_TOKENS,
  size: OPERATOR_SIZE_TOKENS,
  radius: {
    ...OPERATOR_RADIUS_TOKENS
  },
  surface: {
    actionButton: `min-w-0 max-w-full ${OPERATOR_RADIUS_TOKENS.control}`,
    input: `min-w-0 max-w-full ${OPERATOR_RADIUS_TOKENS.control}`,
    nativeSelect: `min-w-0 max-w-full ${OPERATOR_RADIUS_TOKENS.control}`,
    panel: `min-w-0 max-w-full overflow-visible ${OPERATOR_RADIUS_TOKENS.panel} ${OPERATOR_COLOR_TOKENS.surface} ${OPERATOR_COLOR_TOKENS.borderSubtle} shadow-[0_1px_2px_rgba(15,23,42,0.04)]`,
    panelMuted: `min-w-0 max-w-full overflow-visible ${OPERATOR_RADIUS_TOKENS.panel} ${OPERATOR_COLOR_TOKENS.surfaceMuted} ${OPERATOR_COLOR_TOKENS.borderQuiet}`,
    callout: `min-w-0 max-w-full overflow-visible ${OPERATOR_RADIUS_TOKENS.panel} border ${OPERATOR_COLOR_TOKENS.divider} bg-muted/45 py-2`,
    dataTable: `min-w-0 max-w-full overflow-hidden ${OPERATOR_RADIUS_TOKENS.panel} ${OPERATOR_COLOR_TOKENS.surface} ${OPERATOR_COLOR_TOKENS.borderQuiet}`,
    dataTableHeaderRow: "bg-muted/45 hover:bg-muted/45",
    dataTableInteractiveRow: "cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background",
    dataTableRow: "align-top data-[state=selected]:bg-muted/70",
    dataTableRowButton: "h-auto min-h-7 w-full whitespace-normal px-1.5 py-1 text-left leading-snug",
    chartFrame: `aspect-[16/5] min-h-[180px] w-full ${OPERATOR_RADIUS_TOKENS.panel} bg-muted/60 p-3`,
    evidenceBlock: `min-w-0 max-w-full overflow-visible ${OPERATOR_RADIUS_TOKENS.panel} ${OPERATOR_COLOR_TOKENS.surface} ${OPERATOR_COLOR_TOKENS.borderQuiet}`,
    evidenceStatus: `min-w-0 max-w-full overflow-visible ${OPERATOR_RADIUS_TOKENS.control} bg-muted/50 py-2 ${OPERATOR_COLOR_TOKENS.borderSubtle}`,
    emptyState: `min-w-0 max-w-full overflow-visible ${OPERATOR_RADIUS_TOKENS.panel} border ${OPERATOR_COLOR_TOKENS.divider} bg-muted/35 px-0 py-2`,
    field: `grid min-w-0 max-w-full ${OPERATOR_SIZE_TOKENS.compactContentGap} overflow-visible border-t ${OPERATOR_COLOR_TOKENS.divider} bg-transparent px-0 py-3 first:border-t-0`,
    selectionItem: `grid h-auto min-w-0 max-w-full justify-start ${OPERATOR_SIZE_TOKENS.compactContentGap} ${OPERATOR_RADIUS_TOKENS.panel} px-3 py-3 text-left text-sm whitespace-normal ring-1 transition`,
    selectionItemActive: `${OPERATOR_COLOR_TOKENS.accent} ring-primary/25`,
    selectionItemIdle: "bg-card ring-border/60 hover:bg-muted/65",
    stat: "min-w-0 max-w-full",
    tabBadge: `${OPERATOR_RADIUS_TOKENS.badge} bg-muted/70 px-1.5 py-0.5 text-[10px] leading-none text-muted-foreground`
  },
  typography: {
    appTitle: "min-w-0 max-w-full break-words text-sm font-medium leading-snug text-foreground [overflow-wrap:anywhere]",
    appSubtitle: "min-w-0 max-w-full truncate text-xs leading-snug text-muted-foreground",
    eyebrow: "min-w-0 max-w-full break-words text-xs font-medium leading-snug text-muted-foreground [overflow-wrap:anywhere]",
    meta: "min-w-0 max-w-full break-words text-xs font-medium leading-snug text-muted-foreground [overflow-wrap:anywhere]",
    label: "max-w-full break-words text-[11px] font-medium uppercase leading-none tracking-normal text-muted-foreground [overflow-wrap:anywhere]",
    value: "min-w-0 max-w-full break-words text-sm font-medium leading-snug [overflow-wrap:anywhere]",
    calloutValue: "min-w-0 max-w-full break-words text-sm font-semibold leading-snug text-foreground [overflow-wrap:anywhere] sm:text-base",
    detail: "min-w-0 max-w-full break-words text-xs leading-snug text-muted-foreground [overflow-wrap:anywhere]",
    chartCaptionLabel: "min-w-0 max-w-full break-words text-xs font-medium leading-snug text-foreground [overflow-wrap:anywhere]",
    chartCaptionDetail: "min-w-0 max-w-full break-words text-xs leading-snug text-muted-foreground [overflow-wrap:anywhere]",
    statusError: "min-w-0 max-w-full break-words text-sm leading-snug text-destructive [overflow-wrap:anywhere]",
    statusInfo: "min-w-0 max-w-full break-words text-sm leading-snug text-muted-foreground [overflow-wrap:anywhere]",
    statValue: "min-w-0 max-w-full break-words text-lg font-semibold leading-tight tracking-normal [overflow-wrap:anywhere] sm:text-xl",
    tableCell: "min-w-0 max-w-full whitespace-normal break-words align-top text-sm leading-snug [overflow-wrap:anywhere]",
    tableHead: "min-w-0 max-w-full whitespace-normal break-words align-top text-[11px] font-medium uppercase tracking-normal text-muted-foreground [overflow-wrap:anywhere]"
  },
  layout: {
    actionRow: "flex min-w-0 max-w-full flex-wrap items-center gap-2 [&>[data-multiline=true]]:basis-full [&>[data-multiline=true]]:sm:basis-auto",
    appShell: "min-w-0",
    appHeader: `flex ${OPERATOR_SIZE_TOKENS.appHeaderHeight} min-w-0 shrink-0 items-center gap-2 border-b ${OPERATOR_COLOR_TOKENS.divider} bg-background/92 px-3 backdrop-blur sm:gap-3 sm:px-4`,
    appHeaderSeparator: "h-5 bg-border",
    appHeaderCopy: "grid min-w-0 max-w-full gap-0.5",
    appMain: `min-h-[calc(100svh-2.75rem)] min-w-0 overflow-x-hidden ${OPERATOR_COLOR_TOKENS.canvas} ${OPERATOR_SIZE_TOKENS.appMainInset}`,
    page: `mx-auto flex w-full min-w-0 ${OPERATOR_SIZE_TOKENS.pageMaxWidth} flex-col gap-4`,
    pageHeader: "flex min-w-0 max-w-full flex-col gap-2 sm:flex-row sm:items-center sm:justify-between",
    pageHeaderCopy: "grid min-w-0 max-w-full gap-1",
    pageEyebrow: "min-w-0 max-w-full break-words text-xs font-medium leading-snug text-muted-foreground [overflow-wrap:anywhere]",
    pageHeaderTitle: "max-w-full break-words font-heading text-xl font-semibold leading-tight tracking-normal text-foreground [overflow-wrap:anywhere] sm:text-2xl",
    pageHeaderActions: "sm:justify-end",
    contentSection: "grid min-w-0 max-w-full content-start gap-2",
    contentStack: "grid min-w-0 max-w-full gap-3",
    contentStackLoose: "grid min-w-0 max-w-full gap-4",
    mobileOnly: "grid min-w-0 max-w-full gap-2 lg:hidden",
    desktopOnly: "hidden min-w-0 max-w-full lg:block",
    responsiveSplitMd: "grid min-w-0 max-w-full gap-3 md:grid-cols-[minmax(0,1fr)_auto]",
    responsiveSplitLg: "grid min-w-0 max-w-full gap-3 lg:grid-cols-[minmax(0,1fr)_auto]",
    responsiveSplitAlignCenterMd: "md:items-center",
    responsiveSplitAlignCenterLg: "lg:items-center",
    responsiveSplitAlignStartMd: "md:items-start",
    responsiveSplitAlignStartLg: "lg:items-start",
    responsiveSplitContent: "min-w-0 max-w-full",
    responsiveSplitActionsMd: "md:justify-end",
    responsiveSplitActionsLg: "lg:justify-end",
    workspacePanel: "gap-3 p-3 sm:gap-4 sm:p-4",
    workspaceBody: "grid min-w-0 max-w-full gap-4",
    workspaceSplit: "grid min-w-0 max-w-full gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(420px,0.95fr)]",
    workspacePrimary: "min-w-0 max-w-full",
    workspaceInspector: "grid min-w-0 max-w-full content-start gap-3",
    panel: `grid min-w-0 content-start grid-cols-[minmax(0,1fr)] ${OPERATOR_SIZE_TOKENS.panelGap} ${OPERATOR_SIZE_TOKENS.panelPadding}`,
    sectionHeader: "grid min-w-0 max-w-full gap-2 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-start",
    sectionHeaderCopy: "grid min-w-0 max-w-full gap-1",
    sectionTitle: "max-w-full break-words text-base font-semibold leading-snug tracking-normal text-foreground [overflow-wrap:anywhere]",
    sectionHeaderActions: "w-full sm:w-auto sm:justify-end",
    section: "grid min-w-0 max-w-full gap-3",
    calloutContent: "grid min-w-0 max-w-full gap-1.5 px-3",
    emptyStateContent: "grid min-w-0 max-w-full gap-1 px-0",
    evidenceBlockContent: "grid min-w-0 max-w-full gap-3",
    evidencePanel: "grid min-w-0 max-w-full grid-cols-[minmax(0,1fr)] gap-2 [overflow-wrap:anywhere]",
    evidencePanelTitle: "min-w-0 max-w-full break-words text-sm font-semibold leading-snug text-foreground [overflow-wrap:anywhere]",
    evidenceStatusContent: "grid min-w-0 max-w-full gap-1 px-3",
    infoSectionContent: "grid min-w-0 grid-cols-[minmax(0,1fr)] gap-2",
    statContent: "grid min-w-0 max-w-full gap-1",
    selectionItemHeader: "grid min-w-0 max-w-full gap-2 sm:flex sm:items-start sm:justify-between sm:gap-3",
    selectionItemCopy: "grid min-w-0 max-w-full gap-1",
    selectionItemBadge: "min-w-0 max-w-full sm:shrink-0",
    textStack: "grid min-w-0 max-w-full gap-1",
    inlineMeta: "flex min-w-0 max-w-full flex-wrap items-center gap-1",
    fieldGrid: "grid min-w-0 max-w-full gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]",
    compactFieldGrid: "grid min-w-0 max-w-full grid-cols-1 gap-2",
    denseFieldGrid: "grid min-w-0 max-w-full gap-2 sm:grid-cols-2 xl:grid-cols-4",
    dataTable: "table-fixed",
    evidenceRow: "grid min-w-0 max-w-full grid-cols-1 gap-2 [overflow-wrap:anywhere] sm:grid-cols-[repeat(auto-fit,minmax(8rem,1fr))] [&>*]:min-w-0 [&>*]:max-w-full [&>*]:break-words",
    evidenceFieldRowMobileContained: "grid min-w-0 max-w-full grid-cols-[minmax(0,1fr)] gap-2 [overflow-wrap:anywhere] sm:grid-cols-[repeat(auto-fit,minmax(min(100%,8rem),1fr))] [&>*]:min-w-0 [&>*]:max-w-full [&>*]:break-words",
    evidenceFieldMobileContained: "w-full max-w-full overflow-hidden",
    evidenceStack: "grid min-w-0 max-w-full grid-cols-[minmax(0,1fr)] gap-2",
    statGrid: "grid min-w-0 max-w-full grid-cols-1 gap-2 sm:grid-cols-[repeat(auto-fit,minmax(9rem,1fr))]",
    metricStripQuartet: "grid min-w-0 max-w-full grid-cols-1 gap-2 sm:grid-cols-[repeat(auto-fit,minmax(9rem,1fr))] md:grid-cols-4",
    progressTrack: "min-w-0 max-w-full",
    statusStack: "grid min-w-0 max-w-full gap-1",
    statusBadgeMultiline: "h-auto min-h-5 min-w-0 w-full basis-full max-w-full shrink justify-start overflow-visible whitespace-normal break-words text-left leading-snug [overflow-wrap:anywhere] [white-space:normal] sm:w-fit sm:basis-auto",
    chartCaption: "flex min-w-0 flex-wrap items-center justify-between gap-2",
    tabPanel: "flex flex-col gap-4",
    viewTabsList: "max-w-full justify-start overflow-x-auto overscroll-x-contain"
  }
} as const;
