use std::fs;
use std::path::PathBuf;

use super::*;

impl WorkspaceRepository {
    pub fn ingest_source_entry(
        &self,
        input: IngestSourceEntryInput,
    ) -> Result<IngestSourceEntryResult, String> {
        let payload = input
            .body_text
            .clone()
            .or_else(|| input.preview.clone())
            .ok_or_else(|| "ingest source entry requires body_text or preview".to_string())?;
        let time_bucket = utc_hour_bucket(&input.event_time)?;

        let mut collections_index =
            self.read_json_path::<CollectionsIndexFile>(&self.root.join("indexes/collections.json"))?;
        let existing_index = collections_index
            .items
            .iter()
            .position(|item| {
                item.kind == input.kind
                    && item.source_ref == input.source_ref
                    && item.time_bucket == time_bucket
            });

        let (collection_id, created_collection) = match existing_index {
            Some(index) => (collections_index.items[index].collection_id.clone(), false),
            None => (uuid_v7_string(), true),
        };

        let collection_path = self.collection_file_path(&collection_id);
        let entry_shard_path = self.collection_entries_path(&collection_id);
        let mut entries = if entry_shard_path.exists() {
            self.read_ndjson_path::<CollectionEntryFile>(&entry_shard_path)?
        } else {
            Vec::new()
        };

        let blob_id = blob_id_for_contents(&payload);
        let blob_path = self.blob_path(&blob_id);
        FileWorkspaceStore::write_text_if_missing(&blob_path, &payload)?;

        let entry = CollectionEntryFile {
            entry_id: uuid_v7_string(),
            source_ref: input.source_ref.clone(),
            event_time: input.event_time.clone(),
            ingested_at: input.ingested_at.clone(),
            content_hash: blob_id.clone(),
            blob_ref: Some(blob_id.clone()),
            preview: input.preview.clone(),
        };
        entries.push(entry.clone());
        FileWorkspaceStore::write_ndjson_path(&entry_shard_path, &entries)?;

        let time_range = merge_time_range(entries.iter().map(|item| item.event_time.as_str()))?;
        let collection_content_hash = collection_entries_hash(&entries)?;
        let collection_record = CollectionRecordFile {
            collection_id: collection_id.clone(),
            kind: input.kind.clone(),
            source_ref: input.source_ref.clone(),
            time_bucket: time_bucket.clone(),
            time_range: time_range.clone(),
            entry_count: entries.len(),
            content_hash: collection_content_hash.clone(),
            entry_shard_ref: "./entries.ndjson".into(),
            notes: if created_collection {
                Some("Generated by workspace ingestion".into())
            } else {
                None
            },
        };
        self.write_json_path(&collection_path, &collection_record)?;
        self.materialize_collection_entry_documents_for_collection(
            &collection_path,
            &entry_shard_path,
            &collection_record,
            &entries,
        )?;

        let operation_source_ref = input.source_ref.clone();

        let index_item = CollectionIndexItemFile {
            collection_id: collection_id.clone(),
            kind: input.kind,
            source_ref: input.source_ref,
            time_bucket: time_bucket.clone(),
            time_range,
            entry_count: entries.len(),
            content_hash: collection_content_hash,
            path_ref: format!("../collections/items/{collection_id}/collection.json"),
        };

        match existing_index {
            Some(index) => collections_index.items[index] = index_item,
            None => collections_index.items.push(index_item),
        }
        collections_index.items.sort_by(|left, right| {
            right
                .time_bucket
                .cmp(&left.time_bucket)
                .then_with(|| left.source_ref.cmp(&right.source_ref))
        });
        self.write_json_path(&self.root.join("indexes/collections.json"), &collections_index)?;
        self.append_operation(
            "ingest_source_entry",
            "workspace",
            format!(
                "Ingested {} source entry into collection {}.",
                operation_source_ref, collection_id
            ),
            "The service layer materialized a source-centered collection shard, persisted the entry NDJSON append log, and wrote an immutable blob for the entry body.".into(),
            vec![
                self.display_path(&collection_path),
                self.display_path(&entry_shard_path),
                self.display_path(
                    &self.collection_entry_document_path(&collection_id, &entry.entry_id),
                ),
                self.display_path(&blob_path),
            ],
        )?;

        Ok(IngestSourceEntryResult {
            collection_id,
            collection_ref: self.display_path(&collection_path),
            entry_id: entry.entry_id,
            entry_shard_ref: self.display_path(&entry_shard_path),
            time_bucket,
            entry_count: entries.len(),
            blob_id: Some(blob_id),
            created_collection,
        })
    }

    pub fn import_export_bundle(&self, bundle_ref: &str) -> Result<ImportBundleState, String> {
        let source_bundle_path = self.resolve_import_bundle_ref(bundle_ref)?;
        let export_bundle = self.read_json_path::<ExportBundleFile>(&source_bundle_path)?;
        if !export_bundle.sanitized {
            return Err(format!(
                "refusing to import non-sanitized export bundle: {}",
                source_bundle_path.display()
            ));
        }

        let source_root = source_bundle_path.parent().ok_or_else(|| {
            format!(
                "export bundle has no parent directory: {}",
                source_bundle_path.display()
            )
        })?;
        let source_workspace = source_root.join("workspace");
        if !source_workspace.exists() {
            return Err(format!(
                "export bundle workspace is missing: {}",
                source_workspace.display()
            ));
        }

        let import_id = uuid_v7_string();
        let import_root = self.import_root_path(&import_id);
        let import_workspace = import_root.join("workspace");
        fs::create_dir_all(&import_root)
            .map_err(|error| format!("failed to create {}: {error}", import_root.display()))?;
        copy_tree(&source_workspace, &import_workspace, &PathBuf::new())?;

        let metadata = ImportRecordFile {
            import_id: import_id.clone(),
            imported_at: now_label(),
            source_bundle_ref: source_bundle_path.to_string_lossy().replace('\\', "/"),
            bundle_ref: "./bundle/export.json".into(),
            workspace_ref: "./workspace".into(),
            checkpoint_ref: export_bundle.checkpoint_ref.clone(),
            policy_id: export_bundle.policy_id.clone(),
            sanitized: export_bundle.sanitized,
        };
        self.write_json_path(&import_root.join("import.json"), &metadata)?;

        let bundle_destination = import_root.join("bundle");
        fs::create_dir_all(&bundle_destination).map_err(|error| {
            format!("failed to create {}: {error}", bundle_destination.display())
        })?;
        copy_tree(
            &source_bundle_path,
            &bundle_destination.join("export.json"),
            &PathBuf::from("export.json"),
        )?;

        let mut imports_index = if self.imports_index_path().exists() {
            self.read_json_path::<ImportsIndexFile>(&self.imports_index_path())?
        } else {
            ImportsIndexFile { items: Vec::new() }
        };
        imports_index.items.insert(0, metadata.clone());
        self.write_json_path(&self.imports_index_path(), &imports_index)?;
        self.append_operation(
            "import_export_bundle",
            "workspace",
            format!(
                "Staged sanitized export bundle {} as import {}.",
                self.display_path(&source_bundle_path),
                import_id
            ),
            "The service layer copied a sanitized export bundle into the workspace imports area without mutating the active live lane.".into(),
            vec![
                self.display_path(&import_root.join("import.json")),
                self.display_path(&bundle_destination.join("export.json")),
                self.display_path(&import_workspace),
            ],
        )?;

        Ok(ImportBundleState {
            import_id,
            imported_at: metadata.imported_at,
            source_bundle_ref: self.display_path(&source_bundle_path),
            import_ref: self.display_path(&import_root.join("import.json")),
            workspace_ref: self.display_path(&import_workspace),
            checkpoint_ref: metadata.checkpoint_ref,
            policy_id: metadata.policy_id,
            sanitized: metadata.sanitized,
        })
    }

    pub fn activate_import_as_live(&self, import_id: &str) -> Result<BootstrapState, String> {
        let import_path = self.import_file_path(import_id);
        let import_record = self.read_json_path::<ImportRecordFile>(&import_path)?;
        let import_workspace = self.resolve_ref(&import_path, &import_record.workspace_ref);
        let preflight =
            self.build_import_preflight(&import_record, &import_path, &import_workspace)?;
        if preflight.status != "ready" {
            return Err(format!(
                "import {} failed activation preflight: {}",
                import_id, preflight.summary
            ));
        }
        if !import_workspace.exists() {
            return Err(format!(
                "import workspace does not exist: {}",
                import_workspace.display()
            ));
        }

        self.create_checkpoint(
            "incident",
            format!("incident-import-activation-anchor-{}", short_alias_suffix()),
            format!(
                "Automatic pre-activation checkpoint created before activating import {}.",
                import_id
            ),
            "Rollback anchor for staged import activation".into(),
        )?;

        self.replace_workspace_from_root(&import_workspace)?;
        self.normalize_workspace()?;

        let activated_checkpoint = if let Some(checkpoint) =
            self.resolve_checkpoint_record_by_ref(&import_record.checkpoint_ref)?
        {
            self.set_current_checkpoint(&checkpoint)?;
            checkpoint
        } else {
            self.create_checkpoint(
                "incident",
                format!("incident-import-activation-{}", short_alias_suffix()),
                format!(
                    "Imported workspace {} became live without a locally resolvable checkpoint reference.",
                    import_id
                ),
                "Imported live workspace anchored locally after activation".into(),
            )?
        };

        self.record_import_activation_decision(
            import_id,
            &import_record.source_bundle_ref,
            &activated_checkpoint.alias,
        )?;
        let strategy = self.read_json_path::<StrategyManifestFile>(&self.root.join("strategy.json"))?;
        let live_lane_path =
            self.resolve_ref(&self.root.join("strategy.json"), &strategy.active.live_lane_ref);
        let live_lane = self.read_json_path::<LiveLaneFile>(&live_lane_path)?;
        let dashboard_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.dashboard_ref);
        let decisions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.decisions_ref);
        let memory_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.memory_ref);
        let positions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.positions_ref);
        let orders_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.orders_ref);
        self.append_operation(
            "activate_import_as_live",
            "live",
            format!(
                "Activated staged import {} as the current live workspace.",
                import_id
            ),
            "The service layer replaced live asset files with the staged import workspace, preserved service-owned roots, and re-anchored the active checkpoint without bypassing workspace invariants.".into(),
            vec![
                self.display_path(&import_path),
                self.display_path(&import_workspace),
                self.display_path(&self.root.join("strategy.json")),
                self.display_path(&live_lane_path),
                self.display_path(&dashboard_path),
                self.display_path(&decisions_path),
                self.display_path(&memory_path),
                self.display_path(&positions_path),
                self.display_path(&orders_path),
                self.display_path(&self.checkpoint_file_path(&activated_checkpoint.checkpoint_id)),
            ],
        )?;

        self.load_bootstrap_state()
    }

    pub fn pause_global_automation(&self) -> Result<BootstrapState, String> {
        let strategy = self.read_json_path::<StrategyManifestFile>(&self.root.join("strategy.json"))?;
        let live_lane_path =
            self.resolve_ref(&self.root.join("strategy.json"), &strategy.active.live_lane_ref);
        let mut live_lane = self.read_json_path::<LiveLaneFile>(&live_lane_path)?;
        let dashboard_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.dashboard_ref);
        let decisions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.decisions_ref);
        let mut dashboard = self.read_json_path::<DashboardStateFile>(&dashboard_path)?;
        let mut decisions = self.read_json_path::<DecisionLogFile>(&decisions_path)?;

        live_lane.mode = TradingMode::Observer;
        dashboard.mode = TradingMode::Observer;
        dashboard.automation_status = "paused".into();
        dashboard.status_note = Some(
            "Global automation was paused through the service layer while preserving live context."
                .into(),
        );
        prepend_decision(
            &mut decisions.decisions,
            DecisionEntry {
                id: uuid_v7_string(),
                kind: "Control".into(),
                tone: "warning".into(),
                headline: "Global automation paused".into(),
                reason: "The service layer switched the runtime into observer mode without exposing direct workspace mutation to the client.".into(),
                timestamp: now_label(),
            },
        );

        self.write_json_path(&live_lane_path, &live_lane)?;
        self.write_json_path(&dashboard_path, &dashboard)?;
        self.write_json_path(&decisions_path, &decisions)?;
        self.append_operation(
            "pause_global_automation",
            "live",
            "Global automation paused through the service layer.".into(),
            "The service boundary switched the live lane into observer mode without allowing direct client mutation of the workspace.".into(),
            vec![
                self.display_path(&live_lane_path),
                self.display_path(&dashboard_path),
                self.display_path(&decisions_path),
            ],
        )?;

        self.load_bootstrap_state()
    }

    pub fn flatten_all_positions(&self) -> Result<BootstrapState, String> {
        let strategy = self.read_json_path::<StrategyManifestFile>(&self.root.join("strategy.json"))?;
        let live_lane_path =
            self.resolve_ref(&self.root.join("strategy.json"), &strategy.active.live_lane_ref);
        let live_lane = self.read_json_path::<LiveLaneFile>(&live_lane_path)?;
        let dashboard_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.dashboard_ref);
        let decisions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.decisions_ref);
        let positions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.positions_ref);
        let orders_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.orders_ref);

        let mut dashboard = self.read_json_path::<DashboardStateFile>(&dashboard_path)?;
        let mut decisions = self.read_json_path::<DecisionLogFile>(&decisions_path)?;
        let mut positions = self.read_json_path::<PositionsStateFile>(&positions_path)?;
        let mut orders = self.read_json_path::<OrdersStateFile>(&orders_path)?;

        dashboard.status_note =
            Some("Service-layer intervention flattened all live positions in the workspace.".into());
        for metric in dashboard.metrics.iter_mut() {
            if metric.label == "Risk Budget" {
                metric.value = "0%".into();
                metric.delta = "Reset after flatten-all intervention".into();
            }
            if metric.label == "Intervention Load" {
                metric.value = "2 incidents".into();
                metric.delta = "Includes the latest flatten-all incident checkpoint".into();
            }
        }

        positions.current.clear();
        positions.events.insert(
            0,
            LaneEvent {
                event_id: uuid_v7_string(),
                timestamp: now_label(),
                kind: "flatten-all".into(),
                summary: "All live positions were flattened through the service layer.".into(),
            },
        );
        orders.current.clear();
        orders.events.insert(
            0,
            LaneEvent {
                event_id: uuid_v7_string(),
                timestamp: now_label(),
                kind: "flatten-all".into(),
                summary: "All live orders were cleared after the flatten-all intervention.".into(),
            },
        );
        prepend_decision(
            &mut decisions.decisions,
            DecisionEntry {
                id: uuid_v7_string(),
                kind: "Intervention".into(),
                tone: "warning".into(),
                headline: "All live positions flattened".into(),
                reason: "The service layer executed a flatten-all command and reset current positions and orders without bypassing the workspace contract.".into(),
                timestamp: now_label(),
            },
        );

        self.write_json_path(&dashboard_path, &dashboard)?;
        self.write_json_path(&decisions_path, &decisions)?;
        self.write_json_path(&positions_path, &positions)?;
        self.write_json_path(&orders_path, &orders)?;

        let checkpoint = self.create_checkpoint(
            "incident",
            "incident-flatten-all".into(),
            "Client-triggered flatten-all command captured as an incident checkpoint.".into(),
            "Live risk reset to flat".into(),
        )?;
        self.append_operation(
            "flatten_all_positions",
            "live",
            "Flatten-all intervention reset live positions and orders.".into(),
            "The service layer flattened current positions, cleared live orders, and captured an incident checkpoint for the intervention.".into(),
            vec![
                self.display_path(&dashboard_path),
                self.display_path(&decisions_path),
                self.display_path(&positions_path),
                self.display_path(&orders_path),
                self.display_path(&self.checkpoint_file_path(&checkpoint.checkpoint_id)),
            ],
        )?;

        self.load_bootstrap_state()
    }

    pub fn create_export_checkpoint(&self) -> Result<BootstrapState, String> {
        let checkpoint = self.create_checkpoint(
            "export",
            format!("export-{}", short_alias_suffix()),
            "Fresh export checkpoint created before generating a sanitized live-centered bundle."
                .into(),
            "Export policy sanitized-live-centered".into(),
        )?;

        let strategy = self.read_json_path::<StrategyManifestFile>(&self.root.join("strategy.json"))?;
        let live_lane_path =
            self.resolve_ref(&self.root.join("strategy.json"), &strategy.active.live_lane_ref);
        let live_lane = self.read_json_path::<LiveLaneFile>(&live_lane_path)?;
        let dashboard_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.dashboard_ref);
        let decisions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.decisions_ref);
        let export_policy_path =
            self.resolve_ref(&self.root.join("strategy.json"), &strategy.active.export_policy_ref);

        let mut dashboard = self.read_json_path::<DashboardStateFile>(&dashboard_path)?;
        let mut decisions = self.read_json_path::<DecisionLogFile>(&decisions_path)?;
        let export_policy = self.read_json_path::<ExportPolicyFile>(&export_policy_path)?;

        dashboard.status_note = Some(
            "A fresh export checkpoint was created from the current live-centered asset.".into(),
        );
        prepend_decision(
            &mut decisions.decisions,
            DecisionEntry {
                id: uuid_v7_string(),
                kind: "Export".into(),
                tone: "neutral".into(),
                headline: "Export checkpoint created".into(),
                reason: "The service layer created a fresh checkpoint before export so the client can share a stable live-centered asset instead of a drifting mutable state.".into(),
                timestamp: now_label(),
            },
        );

        self.write_json_path(&dashboard_path, &dashboard)?;
        self.write_json_path(&decisions_path, &decisions)?;
        self.create_export_bundle(&checkpoint, &export_policy.policy_id)?;
        self.append_operation(
            "create_export_checkpoint",
            "live",
            format!("Export checkpoint {} created for sanitized sharing.", checkpoint.alias),
            "The service layer created a fresh export checkpoint and materialized a live-centered sanitized export bundle.".into(),
            vec![
                self.display_path(&live_lane_path),
                self.display_path(&dashboard_path),
                self.display_path(&decisions_path),
                self.display_path(&self.checkpoint_file_path(&checkpoint.checkpoint_id)),
                self.display_path(&self.export_bundle_path(&checkpoint.checkpoint_id)),
                self.display_path(&export_policy_path),
            ],
        )?;

        self.load_bootstrap_state()
    }

    pub fn export_checkpoint(&self, checkpoint_id: &str) -> Result<BootstrapState, String> {
        let checkpoint_path = self.checkpoint_file_path(checkpoint_id);
        let checkpoint = self.read_json_path::<CheckpointRecordFile>(&checkpoint_path)?;
        let strategy_path = self.root.join("strategy.json");
        let strategy = self.read_json_path::<StrategyManifestFile>(&strategy_path)?;
        let export_policy_path =
            self.resolve_ref(&strategy_path, &strategy.active.export_policy_ref);
        let export_policy = self.read_json_path::<ExportPolicyFile>(&export_policy_path)?;

        self.create_export_bundle(&checkpoint, &export_policy.policy_id)?;
        self.append_operation(
            "export_checkpoint",
            "workspace",
            format!(
                "Checkpoint {} exported as a sanitized bundle.",
                checkpoint.alias
            ),
            "The service layer materialized a sanitized export bundle from an existing checkpoint without mutating the current live lane.".into(),
            vec![
                self.display_path(&checkpoint_path),
                self.display_path(&self.export_bundle_path(&checkpoint.checkpoint_id)),
                self.display_path(&export_policy_path),
            ],
        )?;

        self.load_bootstrap_state()
    }

    pub fn restore_checkpoint(&self, checkpoint_id: &str) -> Result<BootstrapState, String> {
        let target_checkpoint_path = self.checkpoint_file_path(checkpoint_id);
        let target_checkpoint = self.read_json_path::<CheckpointRecordFile>(&target_checkpoint_path)?;
        let target_alias = target_checkpoint.alias.clone();

        self.create_checkpoint(
            "incident",
            format!("incident-restore-anchor-{}", short_alias_suffix()),
            format!(
                "Automatic pre-restore checkpoint created before restoring {}.",
                target_alias
            ),
            "Rollback anchor for live workspace restore".into(),
        )?;

        let snapshot_root = self.checkpoint_snapshot_path(checkpoint_id);
        self.replace_workspace_from_root(&snapshot_root)?;
        self.normalize_workspace()?;
        self.set_current_checkpoint(&target_checkpoint)?;
        self.record_restore_decision(&target_alias)?;
        let strategy = self.read_json_path::<StrategyManifestFile>(&self.root.join("strategy.json"))?;
        let live_lane_path =
            self.resolve_ref(&self.root.join("strategy.json"), &strategy.active.live_lane_ref);
        let live_lane = self.read_json_path::<LiveLaneFile>(&live_lane_path)?;
        let dashboard_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.dashboard_ref);
        let decisions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.decisions_ref);
        let memory_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.memory_ref);
        let positions_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.positions_ref);
        let orders_path = self.resolve_ref(&live_lane_path, &live_lane.state_refs.orders_ref);
        self.append_operation(
            "restore_checkpoint",
            "live",
            format!("Live workspace restored from checkpoint {}.", target_alias),
            "The service layer restored the selected checkpoint snapshot as the active live workspace and preserved the rollback anchor as an incident checkpoint.".into(),
            vec![
                self.display_path(&target_checkpoint_path),
                self.display_path(&self.root.join("strategy.json")),
                self.display_path(&live_lane_path),
                self.display_path(&dashboard_path),
                self.display_path(&decisions_path),
                self.display_path(&memory_path),
                self.display_path(&positions_path),
                self.display_path(&orders_path),
            ],
        )?;

        self.load_bootstrap_state()
    }
}
